### ISSUE TITLE
Feedback link includes spurious moustache `}`

### ISSUE THREAD

**Issue by MJCallahanPage** [hmrc/address-lookup-frontend#60]
https://github.com/hmrc/address-lookup-frontend/blob/8096e5d888e599412a4685f964fb2f4611f20425/app/model/JourneyConfigDefaults.scala#L103

Same is true for Welsh:
https://github.com/hmrc/address-lookup-frontend/blob/8096e5d888e599412a4685f964fb2f4611f20425/app/model/JourneyConfigDefaults.scala#L142

**Comment by ateohhmrc** [comment]
Fixed by @MJCallahanPage - I have approved and merged the corresponding fix. Closing this issue.
